--- #YAML:1.0
name:               POE-Component-Supervisor
version:            0.06
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Hash::Util::FieldHash::Compat:  0
    Log::Dispatch::Config::TestLog:  0
    MooseX::LogDispatch:  0
    MooseX::POE:          0.210
    namespace::clean:     0
    POE:                  1.0002
    POE::API::Peek:       2.13
    Set::Object:          0
    Test::use::ok:        0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
