--- #YAML:1.0
name:                POE-Component-Supervisor
version:             0.04
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Log::Dispatch::Config::TestLog: 0
    MooseX::LogDispatch:           0
    MooseX::POE:                   0.07
    POE:                           1.0002
    Set::Object:                   0
    Test::use::ok:                 0
    Tie::RefHash:                  0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
