--- #YAML:1.0
name:                POE-Component-Supervisor
version:             0.05
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Hash::Util::FieldHash::Compat: 0
    Log::Dispatch::Config::TestLog: 0
    MooseX::LogDispatch:           0
    MooseX::POE:                   0.07
    namespace::clean:              0
    POE:                           1.0002
    POE::API::Peek:                2.13
    Set::Object:                   0
    Test::use::ok:                 0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
